export const CONSUMER_NAME_COLUMN_WIDTH = 160;
export const CONSUMER_EMAIL_COLUMN_WIDTH = 210;
export const CONSUMER_PHONE_COLUMN_WIDTH = 140;
export const CONSUMER_DELETE_COLUMN_WIDTH = 56;
export const CONSUMER_ROW_HEIGHT = 52;
