import { StyleSheet } from "react-native";
import { DASHBOARD_TABLE_WIDTHS } from "@/constants/dashboard";

export const dashboardStyles = StyleSheet.create({
  container: { flex: 1 },
  flex: { flex: 1 },
  pageHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 10,
  },
  menuButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: "Inter_700Bold",
    color: "#fff",
    letterSpacing: 0.1,
  },
  messName: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: "rgba(255,255,255,0.7)",
    marginTop: 2,
  },
  keyBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(255,255,255,0.16)",
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  keyText: {
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    color: "#fff",
    letterSpacing: 2,
  },
  scrollContent: { paddingTop: 16 },
  mealSection: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 18,
    borderWidth: 1,
    overflow: "hidden",
  },
  dateNav: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingTop: 12,
    paddingBottom: 8,
  },
  dateNavButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  dateCenter: { flex: 1, alignItems: "center", paddingHorizontal: 8 },
  datePrimary: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
  },
  dateSecondary: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    marginTop: 2,
  },
  dateBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#FDE68A",
  },
  dateBannerFuture: {
    backgroundColor: "#EFF6FF",
    borderBottomColor: "#BFDBFE",
  },
  dateBannerText: {
    fontSize: 12,
    fontFamily: "Inter_500Medium",
    color: "#92400E",
  },
  adminBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  mealCountRow: { flexDirection: "row", gap: 8, alignItems: "center" },
  mealCountChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "#F0FDFA",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  mealCountIcon: { fontSize: 13 },
  mealCountNumber: { fontSize: 13, fontFamily: "Inter_700Bold" },
  manageButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#F0FDFA",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#CCFBF1",
  },
  manageButtonText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: "#0F766E",
  },
  mealBoxRow: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  mealBox: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1.5,
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: "center",
    gap: 3,
  },
  mealBoxIcon: { fontSize: 22 },
  mealBoxLabel: {
    fontSize: 11,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
  },
  mealBoxMenu: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    opacity: 0.8,
  },
  menuMarqueeViewport: {
    width: "100%",
    height: 14,
    overflow: "hidden",
    justifyContent: "center",
  },
  menuMarqueeTrack: { flexDirection: "row", alignItems: "center" },
  menuMarqueeText: { flexShrink: 0, lineHeight: 14 },
  mealBoxStatus: {
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
    marginTop: 2,
  },
  mealBoxLoader: { marginTop: 4 },
  mealHint: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    paddingBottom: 10,
  },
  cardsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  balanceHeroCard: {
    width: "100%",
    minHeight: 88,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 18,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  balanceHeroIcon: {
    width: 48,
    height: 48,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  balanceHeroText: { flex: 1, marginLeft: 12, marginRight: 10 },
  balanceHeroLabel: { fontSize: 14, fontFamily: "Inter_700Bold" },
  balanceHeroSub: {
    fontSize: 10,
    lineHeight: 14,
    fontFamily: "Inter_400Regular",
    marginTop: 3,
  },
  balanceHeroValue: {
    maxWidth: "42%",
    fontSize: 23,
    fontFamily: "Inter_700Bold",
    letterSpacing: -0.4,
    textAlign: "right",
  },
  summaryCard: {
    width: "48%",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    gap: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  cardIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  cardLabel: { fontSize: 12, fontFamily: "Inter_500Medium" },
  cardValue: {
    fontSize: 22,
    fontFamily: "Inter_700Bold",
    letterSpacing: -0.3,
  },
  cardSub: { fontSize: 11, fontFamily: "Inter_400Regular" },
  tableCard: {
    marginHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    overflow: "hidden",
    marginBottom: 8,
  },
  tableCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  breakdownIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#CCFBF1",
    borderWidth: 1,
    borderColor: "#99F6E4",
  },
  breakdownHeaderText: { flex: 1, marginLeft: 11 },
  breakdownEyebrow: {
    fontSize: 9,
    lineHeight: 12,
    fontFamily: "Inter_700Bold",
    letterSpacing: 1.1,
    marginBottom: 2,
  },
  tableTitle: {
    fontSize: 16,
    lineHeight: 21,
    fontFamily: "Inter_700Bold",
    letterSpacing: -0.15,
  },
  breakdownHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  customRangeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: "#F5F3FF",
    borderWidth: 1,
    borderColor: "#DDD6FE",
  },
  customRangeBadgeText: {
    color: "#6D28D9",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
  },
  pdfButton: {
    height: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 9,
    borderRadius: 9,
    backgroundColor: "#ECFDF5",
    borderWidth: 1,
    borderColor: "#A7F3D0",
  },
  pdfButtonText: {
    color: "#0F766E",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
  },
  appliedRangeStrip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 14,
    paddingTop: 10,
  },
  appliedRangeLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "#DDD6FE",
  },
  appliedRangeText: {
    color: "#6D28D9",
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
  },
  rangePanel: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: 8,
  },
  rangeFields: { flexDirection: "row", gap: 10 },
  rangeField: { flex: 1, gap: 5 },
  rangeLabel: { fontSize: 11, fontFamily: "Inter_600SemiBold" },
  rangeDropdown: {
    height: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderRadius: 10,
  },
  rangeValue: { flex: 1, fontSize: 12, fontFamily: "Inter_500Medium" },
  rangeApplyButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#7C3AED",
    marginTop: 10,
    paddingVertical: 10,
    borderRadius: 10,
  },
  applyButtonText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  tableScrollWrapper: { position: "relative" },
  fixedConsumerColumn: {
    position: "absolute",
    top: 0,
    left: 0,
    width: DASHBOARD_TABLE_WIDTHS.name + DASHBOARD_TABLE_WIDTHS.rowPadding,
    zIndex: 2,
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  fixedConsumerHeader: {
    height: 38,
    justifyContent: "center",
    paddingLeft: DASHBOARD_TABLE_WIDTHS.rowPadding,
    paddingRight: 8,
  },
  fixedConsumerRow: {
    height: 46,
    justifyContent: "center",
    paddingLeft: DASHBOARD_TABLE_WIDTHS.rowPadding,
    paddingRight: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  fixedConsumerTotal: {
    height: 46,
    justifyContent: "center",
    paddingLeft: DASHBOARD_TABLE_WIDTHS.rowPadding,
    paddingRight: 8,
  },
  tableScrollArrow: {
    position: "absolute",
    right: 7,
    top: 5,
    zIndex: 3,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D1FAE5",
    borderWidth: 1,
    borderColor: "#6EE7B7",
  },
  tableContent: { flexDirection: "column" },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: DASHBOARD_TABLE_WIDTHS.rowPadding,
    height: 38,
  },
  tableBodyRow: { height: 46 },
  tableHeaderText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: "#fff",
  },
  textRight: { textAlign: "right" },
  tableData: { fontSize: 13, fontFamily: "Inter_400Regular" },
  tableDataRight: { textAlign: "right", fontFamily: "Inter_500Medium" },
  tableFooter: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    color: "#fff",
  },
  legend: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  legendText: { fontSize: 11, fontFamily: "Inter_400Regular" },
  summaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#2563EB",
    marginHorizontal: 16,
    marginTop: 12,
    paddingVertical: 14,
    borderRadius: 14,
  },
  summaryButtonText: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
  },
  pickerOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(15,23,42,0.45)",
  },
  pickerCard: {
    width: "100%",
    maxWidth: 380,
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 12,
  },
  pickerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  pickerTitle: { flex: 1, fontSize: 16, fontFamily: "Inter_700Bold" },
  pickerClose: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerMonthRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  pickerArrow: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerMonth: {
    flex: 1,
    textAlign: "center",
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
  },
  pickerWeekRow: { flexDirection: "row" },
  pickerWeekday: {
    width: `${100 / 7}%`,
    textAlign: "center",
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
    paddingVertical: 7,
  },
  pickerGrid: { flexDirection: "row", flexWrap: "wrap" },
  pickerDayCell: {
    width: `${100 / 7}%`,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerDayCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerDayText: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
    fontFamily: "Inter_500Medium",
    includeFontPadding: false,
  },
  emptyState: {
    alignItems: "center",
    gap: 10,
    paddingVertical: 40,
    paddingHorizontal: 40,
  },
  emptyTitle: { fontSize: 16, fontFamily: "Inter_600SemiBold" },
  emptySubtitle: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
  },
});
