import { StyleSheet } from "react-native";
import {
  DAY_CELL_H,
  DAY_CELL_W,
  HEADER_H,
  TOTAL_COL_W,
} from "@/constants/meal";

export const mealStyles = StyleSheet.create({
  container: { flex: 1 },
  flex: { flex: 1 },
  whiteText: { color: "#fff" },
  keyboardScrollSpacer: { height: 320 },
  pageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 15,
    gap: 8,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    shadowColor: "#0F766E",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  menuBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  pageTitle: { fontSize: 20, fontFamily: "Inter_700Bold", letterSpacing: -0.2 },
  addBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  viewOnlyBadge: {
    backgroundColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: 5,
    paddingVertical: 3,
    borderRadius: 8,
  },
  viewOnlyText: {
    color: "#fff",
    fontSize: 7,
    lineHeight: 8,
    fontFamily: "Inter_600SemiBold",
    textAlign: "center",
  },
  monthNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  navBtn: { padding: 6 },
  monthLabel: { fontSize: 15, fontFamily: "Inter_600SemiBold" },
  fillBanner: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  fillBannerText: {
    flex: 1,
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  fillDoneBtn: {
    backgroundColor: "rgba(255,255,255,0.25)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.32)",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
  },
  fillDoneText: { color: "#fff", fontFamily: "Inter_700Bold", fontSize: 13 },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 40,
  },
  emptyTitle: { fontSize: 18, fontFamily: "Inter_600SemiBold" },
  emptySubtitle: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
  },
  gridWrapper: { flex: 1 },
  headerRow: {
    flexDirection: "row",
    height: HEADER_H,
    borderBottomWidth: 1,
  },
  cornerCell: {
    height: HEADER_H,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 6,
  },
  cornerText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    textAlign: "center",
  },
  cornerDiagonal: {
    position: "absolute",
    width: 118,
    height: 1,
    left: -4,
    top: 19,
    backgroundColor: "rgba(255,255,255,0.68)",
    transform: [{ rotate: "20deg" }],
  },
  cornerDateText: {
    position: "absolute",
    top: 4,
    right: 8,
    color: "#fff",
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
  },
  cornerConsumerText: {
    position: "absolute",
    bottom: 4,
    left: 8,
    color: "#fff",
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
  },
  frozenHeaderCell: {
    position: "absolute",
    top: 0,
    left: 0,
    height: HEADER_H,
    zIndex: 30,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 4,
  },
  headerDayCell: {
    width: DAY_CELL_W,
    height: HEADER_H,
    justifyContent: "center",
    alignItems: "center",
  },
  headerDayText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: "#fff",
  },
  totalHeaderCell: {
    width: TOTAL_COL_W,
    height: HEADER_H,
    justifyContent: "center",
    alignItems: "center",
  },
  totalHeaderText: { fontSize: 11, fontFamily: "Inter_700Bold", color: "#fff" },
  dataRow: {
    flexDirection: "row",
    height: DAY_CELL_H,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  nameCell: {
    height: DAY_CELL_H,
    justifyContent: "center",
    paddingHorizontal: 8,
    borderRightWidth: 1,
  },
  frozenNameColumn: {
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 30,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 4,
  },
  nameText: { fontSize: 12, fontFamily: "Inter_500Medium" },
  dayCell: {
    width: DAY_CELL_W,
    height: DAY_CELL_H,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: "#E2E8F0",
    overflow: "visible",
  },
  activeDayCell: {
    borderWidth: 2,
    borderRightWidth: 2,
    backgroundColor: "#E6FFFA",
    zIndex: 10,
    position: "relative",
    alignItems: "stretch",
    justifyContent: "center",
  },
  fillModeCell: {
    backgroundColor: "#E0FFF9",
  },
  todayCell: { borderBottomWidth: 2, borderBottomColor: "#14B8A6" },
  cellInput: {
    flex: 1,
    textAlign: "center",
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    paddingHorizontal: 2,
    paddingVertical: 0,
  },
  fillHandle: {
    position: "absolute",
    bottom: -1,
    right: -1,
    width: 10,
    height: 10,
    borderTopLeftRadius: 2,
    zIndex: 20,
  },
  // Wrapper that catches the press. Anchored flush to the bottom-right
  // corner so the visible button's border touches the cell border. The
  // TouchableOpacity's hitSlop prop extends the tap target beyond the
  // visible button so it's still easy to hit.
  fillHandlePressable: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 30,
  },
  // The visible button: small white chip with a primary border and a
  // Feather "copy" icon. Scales briefly on press for tactile feedback.
  fillHandleBtn: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 1.5,
    elevation: 2,
  },
  dayCellText: { fontSize: 13 },
  rowTotalCell: {
    width: TOTAL_COL_W,
    height: DAY_CELL_H,
    justifyContent: "center",
    alignItems: "center",
  },
  rowTotalText: { fontSize: 14, fontFamily: "Inter_700Bold" },
  totalRow: {
    flexDirection: "row",
    height: DAY_CELL_H + 4,
  },
  totalNameCell: {
    height: DAY_CELL_H + 4,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
  },
  totalNameText: { fontSize: 12, fontFamily: "Inter_700Bold" },
  dayTotalCell: {
    width: DAY_CELL_W,
    height: DAY_CELL_H + 4,
    justifyContent: "center",
    alignItems: "center",
  },
  dayTotalText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },
  grandTotalCell: {
    width: TOTAL_COL_W,
    height: DAY_CELL_H + 4,
    justifyContent: "center",
    alignItems: "center",
  },
  grandTotalText: { fontSize: 15, fontFamily: "Inter_700Bold" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  bottomSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingTop: 12,
    gap: 16,
  },
  sheetHandle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 8,
  },
  sheetHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sheetCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,118,110,0.06)",
  },
  sheetTitle: { fontSize: 18, fontFamily: "Inter_700Bold" },
  sheetSubtitle: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 4,
    marginBottom: 4,
  },
  sheetError: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "#DC2626",
    marginTop: 8,
  },
  sheetInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: "Inter_400Regular",
  },
  sheetActions: { flexDirection: "row", gap: 12 },
  sheetBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
});
