import { StyleSheet } from "react-native";

export const expenseStyles = StyleSheet.create({
  container: { flex: 1 },
  flex: { flex: 1 },
  pageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 15,
    gap: 8,
    borderRadius: 22,
    shadowColor: "#0F766E",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  menuButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  pageTitle: {
    flex: 1,
    fontSize: 20,
    fontFamily: "Inter_700Bold",
    letterSpacing: -0.2,
  },
  viewOnlyBadge: {
    backgroundColor: "rgba(255,255,255,0.22)",
    paddingHorizontal: 5,
    paddingVertical: 3,
    borderRadius: 8,
  },
  viewOnlyText: {
    color: "#fff",
    fontSize: 7,
    lineHeight: 8,
    fontFamily: "Inter_600SemiBold",
    textAlign: "center",
  },
  totalBadge: {
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    paddingHorizontal: 13,
    paddingVertical: 6,
    borderRadius: 20,
  },
  totalBadgeText: { color: "#fff", fontSize: 14, fontFamily: "Inter_700Bold" },
  totalBadgeMember: { paddingHorizontal: 9, paddingVertical: 5 },
  totalBadgeTextMember: { fontSize: 12 },
  columnHeader: { flexDirection: "row", height: 38, alignItems: "center" },
  dayHeaderCell: { justifyContent: "center", alignItems: "center" },
  amountHeaderCell: {
    justifyContent: "center",
    alignItems: "center",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255,255,255,0.38)",
  },
  itemsHeaderCell: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 12,
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255,255,255,0.38)",
  },
  columnHeaderText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: "#fff",
  },
  tableBody: { position: "relative" },
  row: { flexDirection: "row", alignItems: "center", borderBottomWidth: 1 },
  columnDivider: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: "#CBD5E1",
    zIndex: 5,
  },
  dayColumn: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 8,
  },
  dayText: { fontSize: 14, fontFamily: "Inter_500Medium" },
  todayText: { fontFamily: "Inter_700Bold" },
  todayLabel: {
    fontSize: 9,
    fontFamily: "Inter_600SemiBold",
    marginTop: 1,
  },
  amountColumn: {
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 10,
    paddingVertical: 8,
  },
  amountText: { fontSize: 13, fontFamily: "Inter_400Regular" },
  amountValue: { fontFamily: "Inter_600SemiBold" },
  itemsColumn: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  itemsPreviewRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  itemsPreviewText: {
    flex: 1,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  itemCountBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    minWidth: 22,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(15,118,110,0.10)",
  },
  itemCountText: { fontSize: 11, fontFamily: "Inter_700Bold" },
  tapHint: { fontSize: 13, fontFamily: "Inter_400Regular" },
  rowAddButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginLeft: 6,
    flexShrink: 0,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
  },
  totalRow: { flexDirection: "row", height: 50, alignItems: "center" },
  totalLabel: { fontSize: 13, fontFamily: "Inter_700Bold", color: "#fff" },
  totalAmountText: {
    fontSize: 15,
    fontFamily: "Inter_700Bold",
    color: "#fff",
  },
  totalDaysText: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    paddingHorizontal: 12,
    color: "rgba(255,255,255,0.75)",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalSpacer: { flex: 1 },
  bottomSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 12,
    maxHeight: "85%",
  },
  detailSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 12,
    maxHeight: "72%",
  },
  sheetHandle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 16,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sheetTitle: { fontSize: 17, fontFamily: "Inter_700Bold" },
  sheetSubtotal: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    marginTop: 2,
  },
  sheetHeaderActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  clearButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  deleteAllButton: { backgroundColor: "#FEF2F2", borderColor: "#FECACA" },
  detailList: { maxHeight: 360 },
  detailItemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingVertical: 12,
  },
  detailItemIcon: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  detailItemName: { flex: 1, fontSize: 14, fontFamily: "Inter_500Medium" },
  detailItemAmount: { fontSize: 14, fontFamily: "Inter_700Bold" },
  detailItemDeleteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FEF2F2",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 2,
  },
  detailEmptyState: { alignItems: "center", paddingVertical: 34, gap: 10 },
  detailEmptyText: { fontSize: 14, fontFamily: "Inter_400Regular" },
  itemColumnLabels: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 8,
    marginBottom: 4,
    borderBottomWidth: 1,
  },
  itemColumnLabel: { fontSize: 11, fontFamily: "Inter_600SemiBold" },
  itemNameColumnLabel: { flex: 1 },
  itemAmountColumnLabel: { width: 90, textAlign: "right" },
  itemActionColumnLabel: { width: 32 },
  itemsList: { maxHeight: 320 },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  itemNameInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
  },
  itemAmountWrapper: {
    flexDirection: "row",
    alignItems: "center",
    width: 90,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 8,
    paddingRight: 4,
  },
  currencySign: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    marginRight: 2,
  },
  itemAmountInput: {
    flex: 1,
    height: 40,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    padding: 0,
  },
  itemDeleteButton: {
    width: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  addItemButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 12,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1.5,
    borderStyle: "dashed",
    backgroundColor: "rgba(15,118,110,0.04)",
  },
  addItemText: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 16,
    paddingVertical: 15,
    borderRadius: 14,
    shadowColor: "#0F766E",
    shadowOpacity: 0.18,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  saveButtonSubtext: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 14,
    fontFamily: "Inter_500Medium",
  },
  saveButtonText: { color: "#fff", fontSize: 16, fontFamily: "Inter_700Bold" },
});
