import * as Crypto from "expo-crypto";
import type { SQLiteDatabase } from "expo-sqlite";
import type { DepositEntry } from "@/lib/api";
import { OutboxRepository } from "../../repositories/outboxRepository";

type Row={local_id:string;server_id:number|null;user_id:number;mess_id:number;consumer_id:number;amount:number;deposited_at:string;note:string|null;is_deleted:number};
const toEntry=(r:Row):DepositEntry=>({id:r.server_id??-Number.parseInt(r.local_id.replace(/\D/g,"").slice(-12)||"1",10),consumerId:r.consumer_id,amount:Number(r.amount),depositedAt:r.deposited_at,note:r.note});
export class DepositRepository{
 private outbox:OutboxRepository;constructor(private db:SQLiteDatabase){this.outbox=new OutboxRepository(db);}
 async list(userId:number,messId:number,yearMonth:string){const rows=await this.db.getAllAsync<Row>("SELECT * FROM local_deposit_entries WHERE user_id=? AND mess_id=? AND is_deleted=0 AND substr(deposited_at,1,7)=?",userId,messId,yearMonth);return rows.map(toEntry);}
 async replace(userId:number,messId:number,entries:DepositEntry[]){for(const e of entries)await this.db.runAsync(`INSERT INTO local_deposit_entries(local_id,server_id,user_id,mess_id,consumer_id,amount,deposited_at,note,local_updated_at,is_dirty,is_deleted) VALUES(?,?,?,?,?,?,?,?,?,0,0) ON CONFLICT(mess_id,server_id) DO UPDATE SET consumer_id=excluded.consumer_id,amount=excluded.amount,deposited_at=excluded.deposited_at,note=excluded.note,is_deleted=0`,String(e.id),e.id,userId,messId,e.consumerId,e.amount,e.depositedAt,e.note??null,Date.now());}
 async create(userId:number,data:{messId:number;consumerId:number;amount:number;depositedAt:string;note?:string}){const localId=Crypto.randomUUID(),now=Date.now();await this.db.withTransactionAsync(async()=>{await this.db.runAsync("INSERT INTO local_deposit_entries VALUES(?,NULL,?,?,?,?,?,?,?,?,1,0)",localId,userId,data.messId,data.consumerId,data.amount,data.depositedAt,data.note??null,now);await this.outbox.enqueue({userId,messId:data.messId,entityType:"deposit",entityId:localId,operation:"create",dedupeKey:`deposit:${localId}`,payload:{operation:"create",localId,...data}})});const r=await this.db.getFirstAsync<Row>("SELECT * FROM local_deposit_entries WHERE local_id=?",localId);return toEntry(r!);}
 async acknowledgeCreate(localId:string,entry:DepositEntry){await this.db.runAsync("UPDATE local_deposit_entries SET server_id=?,amount=?,deposited_at=?,note=?,is_dirty=0 WHERE local_id=?",entry.id,entry.amount,entry.depositedAt,entry.note??null,localId);}
 async acknowledgeUpdate(localId:string,entry:DepositEntry){await this.db.runAsync("UPDATE local_deposit_entries SET amount=?,deposited_at=?,note=?,is_dirty=0 WHERE local_id=?",entry.amount,entry.depositedAt,entry.note??null,localId);}
 async acknowledgeDelete(localId:string){await this.db.runAsync("DELETE FROM local_deposit_entries WHERE local_id=?",localId);}
 async updateById(userId:number,messId:number,id:number,data:{amount:number;depositedAt:string;note?:string}){const rows=await this.db.getAllAsync<Row>("SELECT * FROM local_deposit_entries WHERE user_id=? AND mess_id=? AND is_deleted=0",userId,messId);const row=rows.find(item=>toEntry(item).id===id);if(!row)throw new Error("Deposit entry is not available offline.");await this.db.runAsync("UPDATE local_deposit_entries SET amount=?,deposited_at=?,note=?,is_dirty=1,local_updated_at=? WHERE local_id=?",data.amount,data.depositedAt,data.note??null,Date.now(),row.local_id);await this.outbox.enqueue({userId,messId,entityType:"deposit",entityId:row.local_id,operation:"update",dedupeKey:`deposit:${row.local_id}`,payload:{operation:row.server_id?"update":"create",localId:row.local_id,serverId:row.server_id,consumerId:row.consumer_id,...data}});return {...toEntry(row),...data};}
 async deleteById(userId:number,messId:number,id:number){const rows=await this.db.getAllAsync<Row>("SELECT * FROM local_deposit_entries WHERE user_id=? AND mess_id=? AND is_deleted=0",userId,messId);const row=rows.find(item=>toEntry(item).id===id);if(!row)throw new Error("Deposit entry is not available offline.");if(row.server_id===null){await this.db.runAsync("DELETE FROM local_deposit_entries WHERE local_id=?",row.local_id);await this.db.runAsync("DELETE FROM offline_outbox WHERE user_id=? AND dedupe_key=?",userId,`deposit:${row.local_id}`);return;}await this.db.runAsync("UPDATE local_deposit_entries SET is_deleted=1,is_dirty=1 WHERE local_id=?",row.local_id);await this.outbox.enqueue({userId,messId,entityType:"deposit",entityId:row.local_id,operation:"delete",dedupeKey:`deposit:${row.local_id}`,payload:{operation:"delete",localId:row.local_id,serverId:row.server_id}});}
}
