import { StyleSheet } from "react-native";
import {
  MEAL_TABLE_COLUMN_WIDTH,
  MEAL_TABLE_NAME_WIDTH,
} from "@/constants/mealStatus";

export const mealStatusStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
  },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  dateNav: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  navArrow: { padding: 6 },
  dateCenter: { alignItems: "center", paddingHorizontal: 8, minWidth: 100 },
  datePrimary: { fontSize: 16, fontFamily: "Inter_700Bold", color: "#fff" },
  dateSub: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    color: "rgba(255,255,255,0.65)",
    marginTop: 1,
  },
  loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center" },
  scrollContent: { paddingTop: 16 },
  card: {
    marginHorizontal: 16,
    marginBottom: 14,
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
  },
  cardTitle: { fontSize: 15, fontFamily: "Inter_700Bold", marginBottom: 14 },
  mealBlock: { paddingVertical: 14 },
  mealHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  mealIcon: { fontSize: 18 },
  mealLabel: { fontSize: 15, fontFamily: "Inter_600SemiBold" },
  flexSpacer: { flex: 1 },
  toggleHint: { fontSize: 12, fontFamily: "Inter_500Medium" },
  menuInput: {
    height: 42,
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    marginBottom: 8,
  },
  windowRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  windowClock: { marginTop: 1 },
  windowHint: { fontSize: 11, fontFamily: "Inter_400Regular" },
  windowInputs: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: "auto",
  },
  timeInput: {
    width: 78,
    height: 34,
    borderWidth: 1.5,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  timeValue: { fontSize: 12, fontFamily: "Inter_500Medium" },
  timeSep: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  timePickerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  timePickerSheet: {
    width: "100%",
    maxWidth: 340,
    alignSelf: "center",
    borderRadius: 22,
    padding: 20,
  },
  timePickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  timePickerTitle: { fontSize: 16, fontFamily: "Inter_700Bold" },
  timePickerClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  timeDisplayPanel: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    padding: 10,
    marginBottom: 10,
  },
  timeDisplayPart: {
    width: 68,
    height: 54,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  timeDisplayPartText: { fontSize: 28, fontFamily: "Inter_700Bold" },
  timeDisplayColon: {
    fontSize: 28,
    fontFamily: "Inter_700Bold",
    marginHorizontal: 4,
  },
  periodStack: { gap: 4, marginLeft: 10 },
  periodChip: {
    width: 42,
    height: 25,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  periodChipText: { fontSize: 11, fontFamily: "Inter_700Bold" },
  clockModeHint: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    textAlign: "center",
    marginBottom: 8,
  },
  clockFace: { position: "relative", alignSelf: "center", marginBottom: 18 },
  clockHandLayer: { position: "absolute", left: 0, top: 0 },
  clockHand: {
    position: "absolute",
    left: "50%",
    marginLeft: -1,
    width: 2,
    borderRadius: 2,
  },
  clockCenterDot: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 10,
    height: 10,
    marginLeft: -5,
    marginTop: -5,
    borderRadius: 5,
  },
  clockNumber: {
    position: "absolute",
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  clockNumberText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  timePickerActions: { flexDirection: "row", gap: 10, marginTop: 2 },
  timePickerClear: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  timePickerClearText: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  timePickerSave: {
    flex: 2,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  timePickerSaveText: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  noticeBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginTop: 14,
    marginBottom: 14,
  },
  noticeText: { fontSize: 11, fontFamily: "Inter_400Regular", flex: 1 },
  readOnlyBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderRadius: 9,
    padding: 10,
    marginBottom: 8,
  },
  readOnlyText: { fontSize: 12, fontFamily: "Inter_500Medium" },
  autoSaveRow: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  autoSaveText: { fontSize: 12, fontFamily: "Inter_500Medium" },
  emptyWrap: { alignItems: "center", paddingVertical: 24, gap: 10 },
  emptyText: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
  },
  tableRow: { flexDirection: "row", alignItems: "center" },
  tableHeader: { borderRadius: 8, marginBottom: 4, paddingVertical: 10 },
  thText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    textAlign: "center",
  },
  thName: { width: MEAL_TABLE_NAME_WIDTH, paddingLeft: 12, textAlign: "left" },
  thMeal: {
    width: MEAL_TABLE_COLUMN_WIDTH,
    alignItems: "center",
    justifyContent: "center",
  },
  tdName: {
    width: MEAL_TABLE_NAME_WIDTH,
    paddingLeft: 12,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
  },
  optedOutCell: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FEF2F2",
    alignItems: "center",
    justifyContent: "center",
  },
  activeCell: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#ECFDF5",
    alignItems: "center",
    justifyContent: "center",
  },
});
