import { StyleSheet } from "react-native";
import { DEPOSIT_DOT_COLOR, DEPOSIT_PRIMARY } from "@/constants/deposit";

export const depositStyles = StyleSheet.create({
  container: { flex: 1 },
  flex: { flex: 1 },
  pageHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 15,
    gap: 8,
    borderRadius: 22,
    shadowColor: DEPOSIT_PRIMARY,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  menuButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  pageTitle: {
    flex: 1,
    color: "#fff",
    fontSize: 18,
    fontFamily: "Inter_700Bold",
    letterSpacing: -0.2,
  },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 8 },
  totalBadge: {
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  totalBadgeText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  addButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  viewOnlyBadge: {
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  viewOnlyText: {
    color: "#fff",
    fontSize: 7,
    lineHeight: 8,
    fontFamily: "Inter_600SemiBold",
    textAlign: "center",
  },
  loadingRow: { paddingVertical: 12, alignItems: "center" },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingBottom: 80,
  },
  emptyTitle: { fontSize: 18, fontFamily: "Inter_700Bold" },
  emptySubtitle: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    paddingHorizontal: 32,
  },
  tableHeader: {
    flexDirection: "row",
    height: 38,
    alignItems: "center",
    borderBottomWidth: 1,
  },
  headerText: {
    color: "#fff",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    paddingHorizontal: 10,
  },
  nameColumn: {
    justifyContent: "center",
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.2)",
  },
  depositsColumn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 6,
    minHeight: 52,
  },
  compactDepositsColumn: {
    minHeight: 0,
    height: "100%",
    paddingVertical: 0,
  },
  totalColumn: {
    justifyContent: "center",
    paddingHorizontal: 10,
    borderRightWidth: 1,
  },
  consumerRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    minHeight: 52,
  },
  nameText: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dotsArea: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    minHeight: 36,
    paddingRight: 4,
  },
  dotsWrapper: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    alignItems: "center",
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: DEPOSIT_DOT_COLOR,
  },
  noDepositsText: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    fontStyle: "italic",
  },
  plusButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
  },
  totalText: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    textAlign: "right",
  },
  grandTotalRow: {
    flexDirection: "row",
    height: 50,
    alignItems: "center",
  },
  grandTotalLabel: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    paddingHorizontal: 10,
  },
  grandTotalText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    textAlign: "right",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  modalSpacer: { flex: 1 },
  bottomSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 36,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },
  historySheet: { maxHeight: "75%" },
  sheetHandle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 16,
  },
  sheetTitle: { fontSize: 18, fontFamily: "Inter_700Bold", marginBottom: 4 },
  sheetTitleNoMargin: { marginBottom: 0 },
  sheetTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  sheetCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetSubtitle: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginBottom: 16,
  },
  sheetFormList: { maxHeight: 320 },
  fieldLabel: {
    fontSize: 12,
    fontFamily: "Inter_500Medium",
    marginBottom: 4,
    marginTop: 10,
  },
  sheetInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    fontFamily: "Inter_400Regular",
  },
  spacedInput: { marginTop: 10 },
  pickerInput: {
    height: 44,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  pickerInputText: { flex: 1, fontSize: 13, fontFamily: "Inter_500Medium" },
  dateTimeRow: { flexDirection: "row" },
  dateField: { flex: 1, marginRight: 8 },
  timeField: { flex: 1 },
  sheetError: {
    color: "#DC2626",
    fontSize: 13,
    marginTop: 8,
    fontFamily: "Inter_400Regular",
  },
  sheetActions: { flexDirection: "row", gap: 10, marginTop: 20 },
  sheetButton: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  sheetButtonText: { color: "#fff", fontFamily: "Inter_600SemiBold" },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  historyTotal: { fontSize: 18, fontFamily: "Inter_700Bold" },
  historyList: { marginTop: 12 },
  entryRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    gap: 10,
  },
  entryDotColumn: { width: 20, alignItems: "center" },
  entryContent: { flex: 1 },
  entryAmount: { fontSize: 15, fontFamily: "Inter_600SemiBold" },
  entryDate: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  entryNote: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    fontStyle: "italic",
    marginTop: 2,
  },
  closeHistoryButton: {
    marginTop: 16,
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: "center",
  },
  pickerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.46)",
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  datePickerSheet: { borderRadius: 20, padding: 18 },
  timePickerSheet: { borderRadius: 20, padding: 20, maxHeight: "88%" },
  pickerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  pickerHeaderActions: { flexDirection: "row", alignItems: "center", gap: 10 },
  pickerCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerTitle: { fontSize: 16, fontFamily: "Inter_700Bold" },
  monthSelectRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  monthArrow: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  monthSelectTitle: { fontSize: 15, fontFamily: "Inter_700Bold" },
  weekdayRow: { flexDirection: "row", marginBottom: 4 },
  weekdayText: {
    width: "14.285%",
    textAlign: "center",
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
  },
  dateGrid: { flexDirection: "row", flexWrap: "wrap" },
  dateCell: {
    width: "14.285%",
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  dateNumber: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  dateCellText: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    lineHeight: 18,
    includeFontPadding: false,
  },
  timePickerDisplay: {
    fontSize: 27,
    fontFamily: "Inter_700Bold",
    marginTop: 2,
  },
  pickerSectionLabel: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    marginBottom: 8,
  },
  timePickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginBottom: 15,
  },
  timePickerOption: {
    width: "14.3%",
    height: 34,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  timePickerOptionText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },
  periodPickerRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: -7,
    marginBottom: 15,
  },
  periodPickerOption: {
    flex: 1,
    height: 36,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  periodPickerText: { fontSize: 13, fontFamily: "Inter_700Bold" },
  pickerConfirmButton: {
    height: 44,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  pickerConfirmText: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
});
