import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#0B5E57" },
  deco1: {
    position: "absolute",
    width: 340,
    height: 340,
    borderRadius: 170,
    backgroundColor: "rgba(255,255,255,0.07)",
    top: -110,
    right: -90,
  },
  deco2: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(255,255,255,0.05)",
    bottom: 80,
    left: -60,
  },
  deco3: {
    position: "absolute",
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "rgba(255,255,255,0.06)",
    top: 140,
    left: -20,
  },
  container: { flexGrow: 1, paddingHorizontal: 24, justifyContent: "center" },
  logoSection: { alignItems: "center", marginBottom: 36 },
  logoCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 10,
  },
  appName: {
    fontSize: 30,
    fontFamily: "Inter_700Bold",
    color: "#fff",
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  tagline: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "rgba(255,255,255,0.72)",
    letterSpacing: 0.1,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 26,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 14,
  },
  cardTitle: {
    fontSize: 21,
    fontFamily: "Inter_700Bold",
    color: "#111827",
    marginBottom: 8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "#6B7280",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
  },
  highlightEmail: { fontFamily: "Inter_600SemiBold", color: "#111827" },
  field: { marginBottom: 18 },
  label: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#374151",
    marginBottom: 7,
  },
  optionalLabel: { color: "#9CA3AF", fontWeight: "400" },
  input: {
    height: 50,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 15,
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    color: "#111827",
    backgroundColor: "#FAFCFF",
  },
  flexibleInput: { flex: 1 },
  passwordRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  eyeBtn: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    backgroundColor: "#FAFCFF",
  },
  forgotRow: { alignItems: "flex-end", marginTop: -6, marginBottom: 10 },
  forgotText: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#0F766E",
  },
  errorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FEF2F2",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FECACA",
    paddingHorizontal: 13,
    paddingVertical: 11,
    marginBottom: 14,
  },
  errorText: {
    flex: 1,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "#DC2626",
    lineHeight: 18,
  },
  submitBtn: {
    height: 54,
    backgroundColor: "#0F766E",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
    shadowColor: "#0F766E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  submitBtnDisabled: { opacity: 0.5, shadowOpacity: 0 },
  submitBtnText: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    color: "#fff",
    letterSpacing: 0.2,
  },
  orRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 20,
    marginBottom: 14,
  },
  orLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "#E5E7EB",
  },
  orText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: "#9CA3AF",
    letterSpacing: 0.8,
  },
  googleBtn: {
    height: 52,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: "#fff",
  },
  googleBtnDisabled: { opacity: 0.5 },
  googleBtnText: {
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    color: "#374151",
  },
  toggleRow: { marginTop: 18, alignItems: "center" },
  toggleText: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "#6B7280",
  },
  toggleLink: { fontFamily: "Inter_700Bold", color: "#0F766E" },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 22,
  },
  backText: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#0F766E",
  },
  iconCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#F0FDFA",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 18,
    borderWidth: 1.5,
    borderColor: "#CCFBF1",
  },
  resetIconCircle: { backgroundColor: "#FFF7ED" },
  otpInput: {
    height: 68,
    borderWidth: 2,
    borderColor: "#0F766E",
    borderRadius: 14,
    fontSize: 30,
    fontFamily: "Inter_700Bold",
    color: "#111827",
    backgroundColor: "#F0FDFA",
    letterSpacing: 12,
    textAlign: "center",
  },
  resendRow: { marginTop: 18, alignItems: "center" },
  resendText: {
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    color: "#0F766E",
  },
  resendTextDisabled: { color: "#9CA3AF" },
});
