import { StyleSheet } from "react-native";

import { CONSUMER_ROW_HEIGHT } from "@/constants/consumerTable";

export const consumerStyles = StyleSheet.create({
  root: { flex: 1 },
  fill: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  headerContent: { flex: 1 },
  backBtn: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  headerTitle: { fontSize: 18, fontFamily: "Inter_700Bold", color: "#fff" },
  headerSub: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: "rgba(255,255,255,0.7)",
    marginTop: 1,
  },
  refreshBtn: { padding: 6 },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    paddingVertical: 0,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 32,
  },
  emptyTitle: { fontSize: 18, fontFamily: "Inter_700Bold", marginTop: 4 },
  emptySubtitle: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
  },
  section: { paddingHorizontal: 16, paddingTop: 16 },
  sectionWithTopMargin: { marginTop: 16 },
  sectionLabel: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 1,
    marginBottom: 8,
    marginLeft: 2,
  },
  tableCard: { borderRadius: 14, borderWidth: 1, overflow: "hidden" },
  theadRow: {
    flexDirection: "row",
    height: 36,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  thCell: { justifyContent: "center", paddingHorizontal: 12 },
  centeredCell: { alignItems: "center" },
  borderedCell: {
    borderLeftWidth: StyleSheet.hairlineWidth,
  },
  th: {
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.8,
  },
  tRow: {
    flexDirection: "row",
    minHeight: CONSUMER_ROW_HEIGHT,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  firstRow: { borderTopWidth: 0 },
  tdCell: {
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  deleteCell: { alignItems: "center", justifyContent: "center" },
  tdName: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  tdBadge: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  tdText: { flex: 1, fontSize: 13, fontFamily: "Inter_400Regular" },
  tdEmpty: { fontSize: 14, fontFamily: "Inter_400Regular" },
  copyRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  copyBtn: {
    width: 26,
    height: 26,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalBox: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 20,
    borderWidth: 1,
    padding: 24,
    alignItems: "center",
    gap: 12,
  },
  modalIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
    backgroundColor: "#FEF2F2",
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
  },
  modalBody: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 20,
  },
  modalConsumerName: { fontFamily: "Inter_600SemiBold" },
  modalBtns: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
    width: "100%",
  },
  modalBtnCancel: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
  },
  modalBtnCancelText: { fontSize: 15, fontFamily: "Inter_600SemiBold" },
  modalBtnDelete: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: "#DC2626",
    alignItems: "center",
  },
  modalBtnDeleteText: {
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    color: "#fff",
  },
});
